# Generated by Django 4.2.6 on 2024-02-27 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.TextField()),
                ("participations", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserLoginLogoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("login", "Giriş"), ("logout", "Çıkış")], max_length=10
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("konu", models.TextField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("joining_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Aktif"), ("Block", "İptal Edildi")],
                        max_length=20,
                    ),
                ),
                (
                    "admin_add_name",
                    models.CharField(
                        choices=[
                            ("user1", "M.Müştak İLBAN"),
                            ("user2", "Nurdagül ERTÜRK"),
                            ("user3", "Pelin KOŞAN"),
                            ("user4", "Aysun OKUMUŞ"),
                            ("user5", "Bahar Koçer"),
                        ],
                        max_length=200,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("deleted_time", models.DateTimeField(blank=True, null=True)),
                ("institution_name", models.CharField(max_length=200)),
                ("contact", models.TextField()),
                ("status_description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Face_to_face", "Yüz Yüze"), ("Phone", "Telefon")],
                        max_length=20,
                    ),
                ),
                (
                    "admin_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
