# Generated by Django 4.2.6 on 2024-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("institution_name", models.TextField()),
                ("contact", models.DateField()),
                ("konu", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Aktif"), ("Block", "İptal Edildi")],
                        max_length=20,
                    ),
                ),
                ("status_description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="userloginlogoutlog",
            name="user",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="konu",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="customer",
            name="admin_add_name",
            field=models.CharField(
                choices=[
                    ("mustakilban", "M.Müştak İLBAN"),
                    ("nurdagülertürk", "Nurdagül ERTÜRK"),
                    ("pelinkosan", "Pelin KOŞAN"),
                    ("aysunokumus", "Aysun OKUMUŞ"),
                    ("baharkocer", "Bahar Koçer"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="end_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="start_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="UserChangeLog",
        ),
        migrations.DeleteModel(
            name="UserLoginLogoutLog",
        ),
    ]
