# Generated by Django 4.2.6 on 2024-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0002_meet_remove_userloginlogoutlog_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
