# Generated by Django 4.2.6 on 2024-02-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0003_alter_customer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="appointment_type",
            field=models.CharField(
                choices=[("İnside", "İç Randevu"), ("Outside", "Dış Randevu")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
