# Generated by Django 4.1 on 2024-04-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('institution_name', models.TextField()),
                ('contact', models.DateField()),
                ('konu', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Aktif'), ('Block', 'İptal Edildi')], max_length=20)),
                ('status_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('participations', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Aktif'), ('Block', 'İptal Edildi')], max_length=20)),
                ('admin_add_name', models.CharField(choices=[('mustakilban', 'M.Müştak İLBAN'), ('nurdagülertürk', 'Nurdagül ERTÜRK'), ('pelinkosan', 'Pelin KOŞAN'), ('aysunokumus', 'Aysun OKUMUŞ'), ('baharkocer', 'Bahar Koçer')], max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=200)),
                ('contact', models.TextField()),
                ('status_description', models.TextField()),
                ('type', models.CharField(choices=[('Face_to_face', 'Yüz Yüze'), ('Phone', 'Telefon')], max_length=20)),
                ('appointment_type', models.CharField(choices=[('İnside', 'İç Randevu'), ('Outside', 'Dış Randevu')], max_length=20)),
                ('admin_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
