# Generated by Django 4.2.6 on 2023-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Randevu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=100)),
                ("tarih", models.DateTimeField()),
                ("randevu_konusu", models.TextField()),
                ("iletisim", models.TextField()),
                ("sonuc_ekranı", models.TextField()),
            ],
        ),
    ]
