# Generated by Django 4.2.6 on 2023-12-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("konu", models.TextField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("joining_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Block", "Block")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
