# Generated by Django 4.2.6 on 2023-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="randevu",
            name="oncelik",
            field=models.IntegerField(
                choices=[(1, "1. Derece öncelikli "), (2, "2. Derece öncelikli")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="randevu",
            name="saatF",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="randevu",
            name="saatS",
            field=models.TimeField(null=True),
        ),
    ]
