# Generated by Django 4.2.6 on 2023-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
