# Generated by Django 4.2.6 on 2023-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0002_events_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="location",
            field=models.CharField(
                default="***********",
                max_length=255,
                null=True,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Event Name"
            ),
        ),
    ]
