# Generated by Django 4.2.6 on 2024-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0002_event_status_alter_customer_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="event",
            name="status_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
