# Generated by Django 4.2.6 on 2024-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0002_userloginlogoutlog_userchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
