# Generated by Django 4.2.6 on 2023-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0003_alter_events_location_alter_events_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="all_day",
            field=models.BooleanField(
                default=True, null=True, verbose_name="All Day Event"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateField(
                default="2023-01-01", null=True, verbose_name="Event Date"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="events",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Düşük"), ("Medium", "Orta"), ("High", "Yüksek")],
                default="Low",
                max_length=10,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
