# Generated by Django 4.2.6 on 2024-02-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0003_customer_deleted_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
