# Generated by Django 4.2.6 on 2023-12-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("randevu", "0003_customer_admin_add_name_alter_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="admin_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
            ),
        ),
    ]
