# Generated by Django 4.2.6 on 2023-12-23 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("randevu", "0004_customer_admin_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="admin_add_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_added_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
