# Generated by Django 4.2.6 on 2024-02-16 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0004_customer_edited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="edited",
        ),
    ]
