# Generated by Django 4.2.6 on 2024-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0005_event_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
