# Generated by Django 4.2.6 on 2024-01-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0009_alter_customer_admin_add_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="delated_appointment",
            field=models.BooleanField(default=False),
        ),
    ]
