# Generated by Django 4.2.6 on 2024-01-02 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0010_customer_delated_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="delated_appointment",
            new_name="deleted",
        ),
    ]
