# Generated by Django 4.2.6 on 2024-02-01 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("randevu", "0012_customer_created_at_customer_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_time",
        ),
    ]
